void initDll();
void GetAPIVersion();
void OpenSpectrometers();
void GetSpectrometersName();
void SetIntegrationTime();
void GetSpectum();
void AsyGetSpectum();
void CloseSpectrometers();		
void MultiChanneTest();